INSERT INTO CATEGORY (ID, NAME) VALUES (1001, 'hardware')
INSERT INTO CATEGORY (ID, NAME) VALUES (1002, 'book')
INSERT INTO CATEGORY (ID, NAME) VALUES (1003, 'audio')

INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'AMAZON')
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'ALIEXPRESS')

INSERT  INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATE_AT) VALUES (1001, 'MOUSE', 1001, 1001, 2, CURRENT_TIMESTAMP)
INSERT  INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATE_AT) VALUES (1002, 'java certified 17', 1001, 1002, 6, CURRENT_TIMESTAMP)
INSERT  INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATE_AT) VALUES (1003, 'MOUSE', 1002, 1001, 3, CURRENT_TIMESTAMP)